In [11]:
import pandas as pd
import os

# PATHS TO YOUR DATASET FOLDERS

folders = [
    "Steam Games Dataset",
    "Steam Store Games (Clean dataset)",
    "Video Game Sales"
]

datasets = {}

# LOAD ALL CSV FILES

for folder in folders:

    print("\n" + "="*60)
    print("Searching in:", folder)

    for root, dirs, files in os.walk(folder):

        for file in files:

            if file.endswith(".csv"):

                filepath = os.path.join(root, file)

                try:

                    df = pd.read_csv(filepath, low_memory=False)

                    dataset_name = file.replace(".csv", "")

                    datasets[dataset_name] = df

                    print(f"\nLoaded: {dataset_name}")
                    print("Shape:", df.shape)

                except Exception as e:

                    print(f"Error loading {file}")
                    print(e)

# SUMMARY OF ALL DATASETS
print("\n")
print("="*60)
print("DATASET SUMMARY")
print("="*60)

for name, df in datasets.items():

    print("\nDataset:", name)
    print("Rows:", df.shape[0])
    print("Columns:", df.shape[1])

# DISPLAY FIRST 5 ROWS OF EACH DATASET

for name, df in datasets.items():

    print("\n")
    print("="*60)
    print(name)
    print("="*60)

    display(df.head())

============================================================
Searching in: Steam Games Dataset

Loaded: games
Shape: (122611, 39)

============================================================
Searching in: Steam Store Games (Clean dataset)

Loaded: steam
Shape: (27075, 18)

Loaded: steamspy_tag_data
Shape: (29022, 372)

Loaded: steam_description_data
Shape: (27334, 4)

Loaded: steam_media_data
Shape: (27332, 5)

Loaded: steam_requirements_data
Shape: (27319, 6)

Loaded: steam_support_info
Shape: (27136, 4)

============================================================
Searching in: Video Game Sales

Loaded: vgsales
Shape: (16598, 11)


============================================================
DATASET SUMMARY
============================================================

Dataset: games
Rows: 122611
Columns: 39

Dataset: steam
Rows: 27075
Columns: 18

Dataset: steamspy_tag_data
Rows: 29022
Columns: 372

Dataset: steam_description_data
Rows: 27334
Columns: 4

Dataset: steam_media_data
Rows: 27332
Columns: 5

Dataset: steam_requirements_data
Rows: 27319
Columns: 6

Dataset: steam_support_info
Rows: 27136
Columns: 4

Dataset: vgsales
Rows: 16598
Columns: 11


============================================================
games
============================================================

,AppID,Name,Release date,Estimated owners,Peak CCU,Required age,Price,DiscountDLC count,About the game,Supported languages,...,Average playtime two weeks,Median playtime forever,Median playtime two weeks,Developers,Publishers,Categories,Genres,Tags,Screenshots,Movies
2539430,Black Dragon Mage Playtest,"Aug 1, 2023",0 - 0,0,0,0.00,0,0,NaN,[],...,0,0,0,NaN,NaN,NaN,NaN,NaN,https://shared.akamai.steamstatic.com/store_it...,NaN
496350,Supipara - Chapter 1 Spring Has Come!,"Jul 29, 2016",0 - 20000,0,0,5.24,65,0,"Springtime, April: when the cherry trees come ...",['English'],...,0,8,0,minori,MangaGamer,"Single-player,Steam Trading Cards,Steam Cloud,...",Adventure,"Adventure,Visual Novel,Anime,Cute",https://shared.akamai.steamstatic.com/store_it...,NaN
1034400,Mystery Solitaire The Black Raven,"May 6, 2019",0 - 20000,0,0,4.99,0,0,"Immerse yourself in the most beloved, mystical...","['English', 'French', 'German', 'Russian']",...,0,0,0,Somer Games,8floor,"Single-player,Family Sharing",Casual,"Casual,Card Game,Solitaire,Puzzle,Hidden Objec...",https://shared.akamai.steamstatic.com/store_it...,NaN
3292190,버튜버 파라노이아 - Vtuber Paranoia,"Oct 31, 2024",0 - 20000,1,0,8.99,0,1,"synopsis 'Hello, I'm Hiyoro, a new YouTuber!' ...",['Korean'],...,0,0,0,유진게임즈,유진게임즈,"Single-player,Steam Achievements,Family Sharing","Casual,Indie,Simulation",NaN,https://shared.akamai.steamstatic.com/store_it...,NaN
3631080,Maze Quest VR,"Apr 24, 2025",0 - 20000,0,0,4.99,0,0,Its not just a Maze; its a Quest! Enter the ca...,['English'],...,0,0,0,Reality Expanded LLC,Reality Expanded LLC,"Single-player,VR Only,Steam Leaderboards,Famil...","Action,Early Access",NaN,https://shared.akamai.steamstatic.com/store_it...,NaN

============================================================
steam
============================================================

,appid,name,release_date,english,developer,publisher,platforms,required_age,categories,genres,steamspy_tags,achievements,positive_ratings,negative_ratings,average_playtime,median_playtime,owners,price
0,10,Counter-Strike,2000-11-01,1,Valve,Valve,windows;mac;linux,0,Multi-player;Online Multi-Player;Local Multi-P...,Action,Action;FPS;Multiplayer,0,124534,3339,17612,317,10000000-20000000,7.19
1,20,Team Fortress Classic,1999-04-01,1,Valve,Valve,windows;mac;linux,0,Multi-player;Online Multi-Player;Local Multi-P...,Action,Action;FPS;Multiplayer,0,3318,633,277,62,5000000-10000000,3.99
2,30,Day of Defeat,2003-05-01,1,Valve,Valve,windows;mac;linux,0,Multi-player;Valve Anti-Cheat enabled,Action,FPS;World War II;Multiplayer,0,3416,398,187,34,5000000-10000000,3.99
3,40,Deathmatch Classic,2001-06-01,1,Valve,Valve,windows;mac;linux,0,Multi-player;Online Multi-Player;Local Multi-P...,Action,Action;FPS;Multiplayer,0,1273,267,258,184,5000000-10000000,3.99
4,50,Half-Life: Opposing Force,1999-11-01,1,Gearbox Software,Valve,windows;mac;linux,0,Single-player;Multi-player;Valve Anti-Cheat en...,Action,FPS;Action;Sci-fi,0,5250,288,624,415,5000000-10000000,3.99

============================================================
steamspy_tag_data
============================================================

,appid,1980s,1990s,2.5d,2d,2d_fighter,360_video,3d,3d_platformer,3d_vision,...,warhammer_40k,web_publishing,werewolves,western,word_game,world_war_i,world_war_ii,wrestling,zombies,e_sports
0,10,144,564,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,550
1,20,0,71,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,30,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,5,122,0,0,0
3,40,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,50,0,77,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

============================================================
steam_description_data
============================================================

,steam_appid,detailed_description,about_the_game,short_description
0,10,Play the world's number 1 online action game. ...,Play the world's number 1 online action game. ...,Play the world's number 1 online action game. ...
1,20,One of the most popular online action games of...,One of the most popular online action games of...,One of the most popular online action games of...
2,30,Enlist in an intense brand of Axis vs. Allied ...,Enlist in an intense brand of Axis vs. Allied ...,Enlist in an intense brand of Axis vs. Allied ...
3,40,Enjoy fast-paced multiplayer gaming with Death...,Enjoy fast-paced multiplayer gaming with Death...,Enjoy fast-paced multiplayer gaming with Death...
4,50,Return to the Black Mesa Research Facility as ...,Return to the Black Mesa Research Facility as ...,Return to the Black Mesa Research Facility as ...

============================================================
steam_media_data
============================================================

,steam_appid,header_image,screenshots,background,movies
0,10,https://steamcdn-a.akamaihd.net/steam/apps/10/...,"[{'id': 0, 'path_thumbnail': 'https://steamcdn...",https://steamcdn-a.akamaihd.net/steam/apps/10/...,NaN
1,20,https://steamcdn-a.akamaihd.net/steam/apps/20/...,"[{'id': 0, 'path_thumbnail': 'https://steamcdn...",https://steamcdn-a.akamaihd.net/steam/apps/20/...,NaN
2,30,https://steamcdn-a.akamaihd.net/steam/apps/30/...,"[{'id': 0, 'path_thumbnail': 'https://steamcdn...",https://steamcdn-a.akamaihd.net/steam/apps/30/...,NaN
3,40,https://steamcdn-a.akamaihd.net/steam/apps/40/...,"[{'id': 0, 'path_thumbnail': 'https://steamcdn...",https://steamcdn-a.akamaihd.net/steam/apps/40/...,NaN
4,50,https://steamcdn-a.akamaihd.net/steam/apps/50/...,"[{'id': 0, 'path_thumbnail': 'https://steamcdn...",https://steamcdn-a.akamaihd.net/steam/apps/50/...,NaN

============================================================
steam_requirements_data
============================================================

,steam_appid,pc_requirements,mac_requirements,linux_requirements,minimum,recommended
0,10,{'minimum': '\r\n\t\t\t<p><strong>Minimum:</st...,{'minimum': 'Minimum: OS X Snow Leopard 10.6....,"{'minimum': 'Minimum: Linux Ubuntu 12.04, Dual...","500 mhz processor, 96mb ram, 16mb video card, ...",NaN
1,20,{'minimum': '\r\n\t\t\t<p><strong>Minimum:</st...,{'minimum': 'Minimum: OS X Snow Leopard 10.6....,"{'minimum': 'Minimum: Linux Ubuntu 12.04, Dual...","500 mhz processor, 96mb ram, 16mb video card, ...",NaN
2,30,{'minimum': '\r\n\t\t\t<p><strong>Minimum:</st...,{'minimum': 'Minimum: OS X Snow Leopard 10.6....,"{'minimum': 'Minimum: Linux Ubuntu 12.04, Dual...","500 mhz processor, 96mb ram, 16mb video card, ...",NaN
3,40,{'minimum': '\r\n\t\t\t<p><strong>Minimum:</st...,{'minimum': 'Minimum: OS X Snow Leopard 10.6....,"{'minimum': 'Minimum: Linux Ubuntu 12.04, Dual...","500 mhz processor, 96mb ram, 16mb video card, ...",NaN
4,50,{'minimum': '\r\n\t\t\t<p><strong>Minimum:</st...,{'minimum': 'Minimum: OS X Snow Leopard 10.6....,"{'minimum': 'Minimum: Linux Ubuntu 12.04, Dual...","500 mhz processor, 96mb ram, 16mb video card, ...",NaN

============================================================
steam_support_info
============================================================

,steam_appid,website,support_url,support_email
0,10,NaN,http://steamcommunity.com/app/10,NaN
1,30,http://www.dayofdefeat.com/,NaN,NaN
2,50,NaN,https://help.steampowered.com,NaN
3,70,http://www.half-life.com/,http://steamcommunity.com/app/70,NaN
4,80,NaN,http://steamcommunity.com/app/80,NaN

============================================================
vgsales
============================================================

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37

In [12]:
import pandas as pd
import os

folders = [
    "Steam Games Dataset",
    "Steam Store Games (Clean dataset)",
    "Video Game Sales"
]

datasets = {}

for folder in folders:
    print("\nSearching folder:", folder)

    for root, dirs, files in os.walk(folder):
        for file in files:
            filepath = os.path.join(root, file)
            name = file.rsplit(".", 1)[0]

            try:
                if file.endswith(".csv"):
                    df = pd.read_csv(filepath, low_memory=False)
                    datasets[name] = df
                    print("Loaded CSV:", filepath, df.shape)

                elif file.endswith(".xlsx"):
                    df = pd.read_excel(filepath)
                    datasets[name] = df
                    print("Loaded Excel:", filepath, df.shape)

            except Exception as e:
                print("Could not load:", filepath)
                print(e)

print("\nLoaded datasets:")
print(datasets.keys())

Searching folder: Steam Games Dataset
Loaded CSV: Steam Games Dataset\games.csv (122611, 39)

Searching folder: Steam Store Games (Clean dataset)
Loaded CSV: Steam Store Games (Clean dataset)\steam.csv (27075, 18)
Loaded CSV: Steam Store Games (Clean dataset)\steamspy_tag_data.csv (29022, 372)
Loaded CSV: Steam Store Games (Clean dataset)\steam_description_data.csv (27334, 4)
Loaded CSV: Steam Store Games (Clean dataset)\steam_media_data.csv (27332, 5)
Loaded CSV: Steam Store Games (Clean dataset)\steam_requirements_data.csv (27319, 6)
Loaded CSV: Steam Store Games (Clean dataset)\steam_support_info.csv (27136, 4)

Searching folder: Video Game Sales
Loaded CSV: Video Game Sales\vgsales.csv (16598, 11)

Loaded datasets:
dict_keys(['games', 'steam', 'steamspy_tag_data', 'steam_description_data', 'steam_media_data', 'steam_requirements_data', 'steam_support_info', 'vgsales'])

In [14]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

games_df = pd.read_csv(
    "Steam Games Dataset/games.csv",
    low_memory=False
)

vgsales_df = pd.read_csv(
    "Video Game Sales/vgsales.csv",
    low_memory=False
)

steam_store_df = pd.read_csv(
    "Steam Store Games (Clean dataset)/steam.csv",
    low_memory=False
)


games_df.columns = (
    games_df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

vgsales_df.columns = (
    vgsales_df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

steam_store_df.columns = (
    steam_store_df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

print("Games Dataset Shape:")
print(games_df.shape)

print("\nVideo Game Sales Dataset Shape:")
print(vgsales_df.shape)

print("\nSteam Store Dataset Shape:")
print(steam_store_df.shape)

print("\nGames Dataset")
display(games_df.head())

print("\nVideo Game Sales Dataset")
display(vgsales_df.head())

print("\nSteam Store Dataset")
display(steam_store_df.head())


os.makedirs("Figures", exist_ok=True)
os.makedirs("Tables", exist_ok=True)


print("\n================ GAMES DATASET COLUMNS ================")
print(games_df.columns.tolist())

print("\n================ VIDEO GAME SALES COLUMNS ================")
print(vgsales_df.columns.tolist())

print("\n================ STEAM STORE DATASET COLUMNS ================")
print(steam_store_df.columns.tolist())

Games Dataset Shape:
(122611, 39)

Video Game Sales Dataset Shape:
(16598, 11)

Steam Store Dataset Shape:
(27075, 18)

Games Dataset

,appid,name,release_date,estimated_owners,peak_ccu,required_age,price,discountdlc_count,about_the_game,supported_languages,...,average_playtime_two_weeks,median_playtime_forever,median_playtime_two_weeks,developers,publishers,categories,genres,tags,screenshots,movies
2539430,Black Dragon Mage Playtest,"Aug 1, 2023",0 - 0,0,0,0.00,0,0,NaN,[],...,0,0,0,NaN,NaN,NaN,NaN,NaN,https://shared.akamai.steamstatic.com/store_it...,NaN
496350,Supipara - Chapter 1 Spring Has Come!,"Jul 29, 2016",0 - 20000,0,0,5.24,65,0,"Springtime, April: when the cherry trees come ...",['English'],...,0,8,0,minori,MangaGamer,"Single-player,Steam Trading Cards,Steam Cloud,...",Adventure,"Adventure,Visual Novel,Anime,Cute",https://shared.akamai.steamstatic.com/store_it...,NaN
1034400,Mystery Solitaire The Black Raven,"May 6, 2019",0 - 20000,0,0,4.99,0,0,"Immerse yourself in the most beloved, mystical...","['English', 'French', 'German', 'Russian']",...,0,0,0,Somer Games,8floor,"Single-player,Family Sharing",Casual,"Casual,Card Game,Solitaire,Puzzle,Hidden Objec...",https://shared.akamai.steamstatic.com/store_it...,NaN
3292190,버튜버 파라노이아 - Vtuber Paranoia,"Oct 31, 2024",0 - 20000,1,0,8.99,0,1,"synopsis 'Hello, I'm Hiyoro, a new YouTuber!' ...",['Korean'],...,0,0,0,유진게임즈,유진게임즈,"Single-player,Steam Achievements,Family Sharing","Casual,Indie,Simulation",NaN,https://shared.akamai.steamstatic.com/store_it...,NaN
3631080,Maze Quest VR,"Apr 24, 2025",0 - 20000,0,0,4.99,0,0,Its not just a Maze; its a Quest! Enter the ca...,['English'],...,0,0,0,Reality Expanded LLC,Reality Expanded LLC,"Single-player,VR Only,Steam Leaderboards,Famil...","Action,Early Access",NaN,https://shared.akamai.steamstatic.com/store_it...,NaN

Video Game Sales Dataset

,rank,name,platform,year,genre,publisher,na_sales,eu_sales,jp_sales,other_sales,global_sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37

Steam Store Dataset

,appid,name,release_date,english,developer,publisher,platforms,required_age,categories,genres,steamspy_tags,achievements,positive_ratings,negative_ratings,average_playtime,median_playtime,owners,price
0,10,Counter-Strike,2000-11-01,1,Valve,Valve,windows;mac;linux,0,Multi-player;Online Multi-Player;Local Multi-P...,Action,Action;FPS;Multiplayer,0,124534,3339,17612,317,10000000-20000000,7.19
1,20,Team Fortress Classic,1999-04-01,1,Valve,Valve,windows;mac;linux,0,Multi-player;Online Multi-Player;Local Multi-P...,Action,Action;FPS;Multiplayer,0,3318,633,277,62,5000000-10000000,3.99
2,30,Day of Defeat,2003-05-01,1,Valve,Valve,windows;mac;linux,0,Multi-player;Valve Anti-Cheat enabled,Action,FPS;World War II;Multiplayer,0,3416,398,187,34,5000000-10000000,3.99
3,40,Deathmatch Classic,2001-06-01,1,Valve,Valve,windows;mac;linux,0,Multi-player;Online Multi-Player;Local Multi-P...,Action,Action;FPS;Multiplayer,0,1273,267,258,184,5000000-10000000,3.99
4,50,Half-Life: Opposing Force,1999-11-01,1,Gearbox Software,Valve,windows;mac;linux,0,Single-player;Multi-player;Valve Anti-Cheat en...,Action,FPS;Action;Sci-fi,0,5250,288,624,415,5000000-10000000,3.99

================ GAMES DATASET COLUMNS ================
['appid', 'name', 'release_date', 'estimated_owners', 'peak_ccu', 'required_age', 'price', 'discountdlc_count', 'about_the_game', 'supported_languages', 'full_audio_languages', 'reviews', 'header_image', 'website', 'support_url', 'support_email', 'windows', 'mac', 'linux', 'metacritic_score', 'metacritic_url', 'user_score', 'positive', 'negative', 'score_rank', 'achievements', 'recommendations', 'notes', 'average_playtime_forever', 'average_playtime_two_weeks', 'median_playtime_forever', 'median_playtime_two_weeks', 'developers', 'publishers', 'categories', 'genres', 'tags', 'screenshots', 'movies']

================ VIDEO GAME SALES COLUMNS ================
['rank', 'name', 'platform', 'year', 'genre', 'publisher', 'na_sales', 'eu_sales', 'jp_sales', 'other_sales', 'global_sales']

================ STEAM STORE DATASET COLUMNS ================
['appid', 'name', 'release_date', 'english', 'developer', 'publisher', 'platforms', 'required_age', 'categories', 'genres', 'steamspy_tags', 'achievements', 'positive_ratings', 'negative_ratings', 'average_playtime', 'median_playtime', 'owners', 'price']

In [7]:
games_df = datasets['games']
vgsales_df = datasets['vgsales']

In [ ]:
steam_store_df = pd.read_csv(
    "Steam Store Games (Clean dataset)/steam.csv",
    low_memory=False
)

print(steam_store_df.shape)
print(steam_store_df.columns.tolist())